name: "Build Haskell - Cabal"
description: "Build haskell project with cabal"


inputs:

  cabal-version:
    description: "Version of cabal to use"
    required: false
    default: "3.8.1.0"

  ghc-version:
    description: "Version of ghc to use"
    required: false
    default: "9.2.5"

  package:
    description: "Name of the package to build and test"
    required: true


runs:
  using: "composite"
  steps:
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell and Cabal
      with:
        ghc-version: ${{ inputs.ghc-version }}
        cabal-version: ${{ inputs.cabal-version }}

    - name: Configure Cabal settings
      shell: bash
      run: |
        cabal configure -O0 --flags="pedantic"

    - name: Freeze
      shell: bash
      run: |
        cabal freeze
        head -n -1 cabal.project.freeze > deps

    - uses: actions/cache@v2.1.3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ inputs.ghc-version }}-${{ hashFiles('deps') }}

    - name: Install dependencies
      shell: bash
      run: |
        cabal build ${{ inputs.package }} --only-dependencies

    - name: Build
      shell: bash
      run: |
        cabal build ${{ inputs.package }}

    - name: Test
      shell: bash
      run: |
        cabal test ${{ inputs.package }}
