name: message-db
version: 0.0.0.1

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe

default-extensions:
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StrictData
  - TypeApplications

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - postgresql-simple
    - safe-exceptions
    - text
    - time
    - uuid

tests:
  message-db-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - bytestring
      - containers
      - hedgehog
      - hspec
      - hspec-hedgehog
      - message-db
      - postgres-options
      - postgresql-simple
      - tmp-postgres
      - typed-process
      - unliftio
