name: message-db
version: 0.0.0.1

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe

default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - NumericUnderscores
  - StrictData
  - TypeApplications
  - TypeFamilies
  - TypeOperators

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - containers
    - directory
    - exceptions
    - filepath
    - immortal
    - mtl
    - parsec
    - postgresql-simple
    - safe-exceptions
    - text
    - time
    - transformers
    - unliftio-core
    - uuid

tests:
  message-db-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - bytestring
      - directory
      - exceptions
      - filepath
      - message-db
      - mtl
      - postgresql-simple
      - text
      - time
      - transformers
      - unliftio
      - uuid
