name: "message-db-monad-cicd"


on:
  push:
    branches: ["main"]
    tags: ["message-db-monad/*.*.*.*"]
    paths:
      - "message-db-monad/**"
  pull_request:
    branches: ["main"]
    paths:
      - "message-db-monad/**"


jobs:

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Set up hlint"
        uses: haskell/actions/hlint-setup@v2
        with:
          version: "3.5"

      - name: "Run hlint"
        uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning
          path: message-db-monad/src/


  fourmolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Run fourmolu"
        uses: fourmolu/fourmolu-action@v5
        with: 
          pattern: |
            message-db-monad/**/*.hs


  cabal:
    name: cabal ${{ matrix.cabal }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        cabal: ["3.8.1.0"]
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.5"
          - "9.4.3"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Setup system dependencies"
        uses: "./.github/actions/setup-system-dependencies"

      - uses: "./.github/actions/cabal-build"
        name: Build
        with:
          package: message-db-monad
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}


  stack:
    name: stack ${{ matrix.stack }} / ${{ matrix.resolver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        stack: ["2.9.1"]
        resolver:
          - "lts-18"
          - "lts-19"
          - "nightly"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Setup system dependencies"
        uses: "./.github/actions/setup-system-dependencies"

      - uses: "./.github/actions/stack-build"
        name: Build
        with:
          package: message-db-monad
          resolver: ${{ matrix.resolver }}
          stack-version: ${{ matrix.stack }}


  # publish:
  #   name: "publish"
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: "ubuntu-latest"
  #   needs:
  #     - hlint
  #     - fourmolu
  #     - cabal
  #     - stack
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: true
  #
  #     - uses: "./.github/actions/publish"
  #       name: Publish package
  #       with:
  #         package: message-db-monad
  #         candidate: "true"
  #         hackage_user: ${{ secrets.HACKAGE_USER }}
  #         hackage_password: ${{ secrets.HACKAGE_PASSWORD }}
