name: "message-db-monad-ci"

on:
  push:
    branches: ["main"]
    paths:
      - "message-db-monad/**"

  pull_request:
    branches: ["main"]
    paths:
      - "message-db-monad/**"

jobs:
  cabal:
    name: cabal ${{ matrix.cabal }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        cabal: ["3.6"]
        ghc:
          - "8.10"
          - "9.0"
          - "9.2"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Setup system dependencies"
        uses: "./.github/actions/setup-system-dependencies"

      - uses: "./.github/actions/cabal-build"
        name: Build
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          package: message-db-monad

  stack:
    name: stack ${{ matrix.stack }} / ${{ matrix.resolver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        stack: ["2.7"]
        resolver:
          - "lts-18"
          - "lts-19"
          - "nightly"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Setup system dependencies"
        uses: "./.github/actions/setup-system-dependencies"

      - uses: "./.github/actions/stack-build"
        name: Build
        with:
          resolver: ${{ matrix.resolver }}
          stack-version: ${{ matrix.stack }}
          package: message-db-monad

  # publish:
  #   name: "publish"
  #   runs-on: "ubuntu-latest"
  #   needs:
  #     - cabal
  #     - stack
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #
  #     - uses: "./.github/actions/publish"
  #       name: Publish candidate package
  #       with:
  #         package: message-db-monad
  #         candidate: "true"
  #         hackage_user: ${{ secrets.HACKAGE_USER }}
  #         hackage_password: ${{ secrets.HACKAGE_PASSWORD }}
