name: "message-db-cd"

on:
  create:
    tags:
      - "message-db/**"

jobs: 
  build:
    name: "build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Setup system dependencies"
        uses: "./.github/actions/setup-system-dependencies"

      - uses: "./.github/actions/cabal-build"
        name: Build
        with:
          package: message-db

  publish:
    name: "publish"
    runs-on: "ubuntu-latest"
    needs:
      - build

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: "./.github/actions/publish"
        name: Publish package
        with:
          package: message-db
          candidate: "false"

